[project]
name = "python-stopwatch2"
version = "2.0.0"
description = "A simple library to measure code performance."
authors = [
  { name = "Rafael", email = "contact.devrma@gmail.com" },
  { name = "Jonghwan Hyeon", email = "hyeon0145@gmail.com" },
]
maintainers = [{ name = "Rafael", email = "contact.devrma@gmail.com" }]
license = "MIT"
readme = "README.md"
requires-python = ">=3.10"
keywords = ["stopwatch", "timer", "time", "profile"]
dynamic = ["classifiers"]
dependencies = ["colorama (>=0.4.6,<0.5.0)"]

[project.urls]
homepage = "https://stopwatch2.vercel.app/"
repository = "https://github.com/devRMA/python-stopwatch2"
documentation = "https://stopwatch2.vercel.app/guide/getting-started.html"

[tool.poetry]
requires-poetry = ">=2.0"
packages = [{ include = "stopwatch" }]

[tool.poetry.group.dev.dependencies]
mypy = ">=2.3.0"
pytest = ">=9.1.1"
pytest-cov = ">=7.1.0"
ruff = ">=0.16.1"
types-colorama = ">=0.4.15"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 79
target-version = "py310"

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint]
select = ["E", "F", "W", "I", "UP", "B", "RUF"]

[tool.mypy]
python_version = "3.10"
strict = true
